language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '8'
  - '7'
before_script:
  - npm prune
  - npm install
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
